[package]
name = "rusty_dart_lib"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "rusty_dart"
# crate-type = ["cdylib"]

[dependencies]
flutter_rust_bridge = "1.61.1"
libc = "0.2"
notify = "5.0.0"
