name: rusty_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  ffi: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  ffigen: ^7.2.4
  lints: ^2.0.1
  test: ^1.22.2
# ffigen:
#   output: "generated_bindings.dart"
#   headers:
#     entry-points:
#       - "example.h"
